-- 002_document_schema.sql — records the schema decisions inside the database.
--
-- Why this migration exists (Issue #37): 001_init.sql was written while the
-- development database was PostgreSQL 9.3, and its header explains the column
-- types as consequences of that version. The server is postgres:17 now
-- (Issue #35), so the header no longer describes reality - but it cannot be
-- edited: pkg/migrate stores the SHA-256 of every applied file and refuses to
-- start when the content of a migration that already ran differs from the
-- stored checksum (pkg/migrate/migrate.go). Rewriting history in place would
-- break every environment where 001 has been applied.
--
-- So the corrected description lives here, as COMMENT ON: it is stored in the
-- catalog, readable with \d+ from inside the database, and it does not touch a
-- single byte of the migration that already ran.
--
-- Neither of the two features the old note apologises for is worth adding now:
--
--   * id is generated by the application on purpose, not because
--     gen_random_uuid() was unavailable. domain.NewUser assigns the identifier
--     while building the aggregate, so the identity of a new account is known
--     before the row exists and can already be used to open a session or to
--     answer the POST that registered it. A DEFAULT would move that decision
--     into the INSERT and force a RETURNING round trip for a value that is
--     valid long before it reaches the database.
--   * e-mail stays a plain VARCHAR because the domain layer normalizes the
--     address before storing it (internal/domain), which makes the unique index
--     compare two already comparable values. CITEXT would move that rule into
--     the database, change what the unique index means, and add a contrib
--     dependency, only to re-implement an invariant the domain already keeps.
--
-- COMMENT ON replaces an existing comment instead of failing, so this file is
-- safe both on a fresh database and on one that already carries the schema.

COMMENT ON TABLE users IS
    'Library accounts, staff and readers alike. Identifiers are generated by the service rather than by the database: the aggregate needs its id before the INSERT. See migrations/README.md for the history of these column types.';

COMMENT ON COLUMN users.id IS
    'Application-generated UUID (domain.NewUser). Deliberately without DEFAULT gen_random_uuid(): the identity of an account must be known before its row exists.';

COMMENT ON COLUMN users.email IS
    'Normalized by the domain layer before it is stored; users_email_key is the final arbiter of uniqueness. Plain VARCHAR is a decision, not a workaround: CITEXT would move a rule the domain already enforces into the database and change the meaning of that index.';

COMMENT ON COLUMN users.phone IS
    'Digits as validated and stored by the domain layer; no phone extension module is required.';

COMMENT ON TABLE sessions IS
    'Bearer tokens. Only the SHA-256 of a token is stored, so a dump of this table cannot be replayed against the API.';
