-- Users of the library: staff and readers alike.
--
-- Notes on the types, both of them consequences of supporting PostgreSQL 9.3:
--   * the primary key is a UUID generated by the application, because
--     gen_random_uuid() only exists from 9.4 (and needs pgcrypto before that);
--   * e-mail and phone are plain VARCHAR, CITEXT and the phone extensions would
--     make the deployment depend on contrib modules. Normalization happens in
--     the domain layer (internal/domain), the database only stores the result.

CREATE TABLE users (
    id            UUID          PRIMARY KEY,
    email         VARCHAR(254)  NOT NULL,
    password_hash TEXT          NOT NULL,
    full_name     VARCHAR(120)  NOT NULL,
    phone         VARCHAR(20)   NOT NULL DEFAULT '',
    role          VARCHAR(16)   NOT NULL DEFAULT 'READER',
    status        VARCHAR(16)   NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ,
    CONSTRAINT users_role_check   CHECK (role IN ('READER', 'LIBRARIAN')),
    CONSTRAINT users_status_check CHECK (status IN ('ACTIVE', 'DEACTIVATED')),
    CONSTRAINT users_name_check   CHECK (length(full_name) >= 2)
);

-- The login of a user is the normalized e-mail. A unique index is the only
-- place where a concurrent registration of the same address can be decided.
CREATE UNIQUE INDEX users_email_key ON users (email);

-- The staff list is filtered by role and status and sorted by registration
-- date; this index serves both.
CREATE INDEX users_role_status_idx ON users (role, status);
CREATE INDEX users_created_at_idx ON users (created_at DESC);

-- Bearer tokens. Only the SHA-256 of a token is stored, so a dump of this
-- table cannot be replayed against the API.
CREATE TABLE sessions (
    id         UUID        PRIMARY KEY,
    user_id    UUID        NOT NULL,
    token_hash CHAR(64)    NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Lookup by token is on the hot path of every authorized request.
CREATE UNIQUE INDEX sessions_token_hash_key ON sessions (token_hash);

-- "My sessions" and the cascade of a deactivation both read by user. The
-- expiration sweep is a range scan over expires_at.
CREATE INDEX sessions_user_id_idx ON sessions (user_id, created_at DESC);
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);
