// Package docs exposes the OpenAPI document that protoc-gen-openapiv2
// generates from the proto contract. The file is regenerated by
// scripts/gen_proto.ps1 and embedded into the binary so that the service
// serves its own Swagger documentation without external files.
package docs

import _ "embed"

// SwaggerJSON is the Swagger 2.0 specification of book.v1.BookService.
//
//go:embed book/v1/book.swagger.json
var SwaggerJSON []byte
